name: preo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0-259.0.dev

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  dart_style: ^3.0.1
  flutter_svg: ^2.0.17
  flutter_animate: ^4.5.2
  get: ^4.6.6
  intl: ^0.20.2
  smooth_page_indicator: ^1.2.0+3
  form_validator: ^2.1.1
  pinput: ^5.0.1
  http: ^1.3.0
  flutter_gen: ^5.9.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner:
  flutter_gen_runner:

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/teams/
    - assets/images/explainer/
    - assets/logos/
    - assets/images/splash/
    - assets/images/png/
    - assets/icons/eye.svg
    - assets/icons/eye_slash.svg
    - assets/icons/calendar.svg

  generate: true



  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf
